doctrine:
  dbal:
#    driver: 'pdo_mysql'
    url: '%env(resolve:DATABASE_URL)%'
#    server_version: '8.4.4'
    charset: utf8mb4
#    default_table_options: { charset: utf8mb4, collate: utf8mb4_unicode_ci }
  orm:
#    auto_generate_proxy_classes: false
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true

#    enable_lazy_ghost_objects: true

# a décomenter si php >= 8.4
#    enable_native_lazy_objects: true

    controller_resolver:
        auto_mapping: true

    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
