framework:
  rate_limiter:
    contact_form:
      policy: 'sliding_window'
      limit: 5
      interval: '10 minutes'
    reset_password_requests:
      policy: 'sliding_window'
      limit: 5
      interval: '15 minutes'
    login_form:
      policy: 'sliding_window'
      limit: 10
      interval: '1 minute'

