framework:
  messenger:
    failure_transport: failed
    transports:
      async: 'doctrine://default'
      failed: 'doctrine://default?queue_name=failed'
    routing:
      'Symfony\Component\Mailer\Messenger\SendEmailMessage': async

